### ISSUE TITLE
how can i train model on my own dataset

### ISSUE THREAD

**Issue by pro-xuchao** [khokao/diffusion-autoencoders#6]
according what you said, two datasets are supported, CelebA and  CelebA-HQ. If I want to train the model on my own dataset, what should i do to change the code?

**Comment by khokao** [comment]
Hi @pro-xuchao , thanks for asking!

If you wish to train Diffusion Autoencoders using your own dataset, you should replace `self.dataset`, which is obtained in the [_init_dataset](https://github.com/khokao/diffusion-autoencoders/blob/0b293c53194188c1793a4bd4452017bc3eaeda53/diffae/interface.py#L122) function, with your dataset. The dataset should yield two variables: an image and a target. However, since the target is not utilized during the training of Diffusion Autoencoders, returning a dummy variable would suffice.

Then, if you also want to train a multi-label classifier, the target should be a binary vector and adjust the value of `num_class` in the cfg yaml file you use. (The default value is 40 since the target in CelebA is 40 attributes).

**Comment by pro-xuchao** [comment]
Thank you for your response. Another question is: when train the DiffusionAutoEncoder, only the unet( to calucate noises) branch was optimizaed by simple loss. But the semanticEncoder did not change during trainning? I definitely have made some mistakes, but I could not find it. Can you tell me how semanticEncoder was optimizaed in your code?

**Comment by khokao** [comment]
> the semanticEncoder did not change during trainning?

No, the parameters of SemanticEncoder change during training.
Unet receives the features obtained by SemanticEncoder; both Unet and SemanticEncoder are optimized simultaneously.
https://github.com/khokao/diffusion-autoencoders/blob/0b293c53194188c1793a4bd4452017bc3eaeda53/diffae/models/model.py#L7-L37
